version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL}
    restart: always