version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL}
      - NITRO_PORT=4000
    restart: always