version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always