services:
  nuxt:
    container_name: nuxt_app
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL}
      - NITRO_PORT=4000
    restart: unless-stopped
