name: Deploy Nuxt 3 App

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git tag -l --sort=-v:refname | head -n 1)
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Generate new version
        id: create_tag
        run: |
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="v1.0.0"
          else
            NEW_TAG=$(echo $LATEST_TAG | awk -F. '{$NF++; print $0}' OFS=.)
          fi
          echo "New tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create new tag
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}



  # deploy:
  #   needs: tag_release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Deploy to server
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: |
  #           cd /home/${{ secrets.SSH_USER }}/nuxt-app
  #           git pull origin main
  #           git checkout ${{ needs.tag_release.outputs.new_tag }}
  #           docker compose down
  #           docker compose build --no-cache
  #           docker compose up -d --force-recreate
  #           docker image prune -f
